import {
  Activity,
  Airplay,
  Anchor,
  Archive,
  BarChart3,
  BookOpen,
  Bot,
  Boxes,
  Briefcase,
  Calendar,
  Camera,
  ChartLine,
  Cloud,
  Code,
  Code2,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Film,
  Flame,
  Folder,
  FolderKanban,
  Gamepad2,
  Globe,
  Headphones,
  Heart,
  Image,
  Key,
  Layers,
  LayoutGrid,
  Package,
  Rocket,
  Server,
  Settings,
  ShoppingCart,
  Smartphone,
  Star,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const PROJECT_COLORS: readonly string[] = [
  "#000000",
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#14b8a6",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#6b7280",
] as const;

export const PROJECT_COLOR_LABELS: Record<string, string> = {
  "#000000": "Negro",
  "#ef4444": "Rojo",
  "#f97316": "Naranja",
  "#eab308": "Amarillo",
  "#22c55e": "Verde",
  "#14b8a6": "Teal",
  "#06b6d4": "Cyan",
  "#3b82f6": "Azul",
  "#8b5cf6": "Violeta",
  "#ec4899": "Rosa",
  "#6b7280": "Gris",
};

export interface ProjectIconEntry {
  name: string;
  label: string;
  icon: LucideIcon;
}

export const PROJECT_ICONS: readonly ProjectIconEntry[] = [
  { name: "Activity", label: "Actividad", icon: Activity },
  { name: "Airplay", label: "AirPlay", icon: Airplay },
  { name: "Anchor", label: "Ancla", icon: Anchor },
  { name: "Archive", label: "Archivo", icon: Archive },
  { name: "BarChart3", label: "Gráfico de barras", icon: BarChart3 },
  { name: "BookOpen", label: "Libro", icon: BookOpen },
  { name: "Bot", label: "Bot", icon: Bot },
  { name: "Boxes", label: "Cajas", icon: Boxes },
  { name: "Briefcase", label: "Maletín", icon: Briefcase },
  { name: "Calendar", label: "Calendario", icon: Calendar },
  { name: "Camera", label: "Cámara", icon: Camera },
  { name: "ChartLine", label: "Gráfico de líneas", icon: ChartLine },
  { name: "Cloud", label: "Nube", icon: Cloud },
  { name: "Code", label: "Código", icon: Code },
  { name: "Code2", label: "Código 2", icon: Code2 },
  { name: "Cpu", label: "CPU", icon: Cpu },
  { name: "CreditCard", label: "Tarjeta", icon: CreditCard },
  { name: "Database", label: "Base de datos", icon: Database },
  { name: "FileText", label: "Documento", icon: FileText },
  { name: "Film", label: "Película", icon: Film },
  { name: "Flame", label: "Llama", icon: Flame },
  { name: "Folder", label: "Carpeta", icon: Folder },
  { name: "FolderKanban", label: "Tablero", icon: FolderKanban },
  { name: "Gamepad2", label: "Juegos", icon: Gamepad2 },
  { name: "Globe", label: "Globo", icon: Globe },
  { name: "Headphones", label: "Auriculares", icon: Headphones },
  { name: "Heart", label: "Corazón", icon: Heart },
  { name: "Image", label: "Imagen", icon: Image },
  { name: "Key", label: "Llave", icon: Key },
  { name: "Layers", label: "Capas", icon: Layers },
  { name: "LayoutGrid", label: "Cuadrícula", icon: LayoutGrid },
  { name: "Package", label: "Paquete", icon: Package },
  { name: "Rocket", label: "Cohete", icon: Rocket },
  { name: "Server", label: "Servidor", icon: Server },
  { name: "Settings", label: "Ajustes", icon: Settings },
  { name: "ShoppingCart", label: "Tienda", icon: ShoppingCart },
  { name: "Smartphone", label: "Móvil", icon: Smartphone },
  { name: "Star", label: "Estrella", icon: Star },
  { name: "Wrench", label: "Herramienta", icon: Wrench },
  { name: "Zap", label: "Rayo", icon: Zap },
];

export const PROJECT_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  PROJECT_ICONS.map((entry) => [entry.name, entry.icon])
);